# Copyright 2019 PrivateStorage.io, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

jobs:
  build:
    docker:
      - image: "nixos/nix:2.2.1"
    steps:
      - run:
          name: "Install CA Certificates"
          command: |
            # Required for cache and artifact interactions.  Though we use a
            # nix image, it's actually an alpine base...  The CircleCI cache
            # management and artifact uploader doesn't know how to use the nix
            # ca bundle we could install.
            apk update
            apk add ca-certificates

      - run:
          name: "Install Git"
          command: |
            # Required for the checkout step
            nix-env -i git openssh

      - restore_cache:
          keys:
            - "v1-nix-store"

      - "checkout"

      - run:
          name: "Nix Build"
          command: |
            nix-build

      - save_cache:
          key: "v1-nix-store"
          paths:
            - "/nix/store"

      - store_artifacts:
          path: "result/docs"
          destination: "docs"

workflows:
  version: 2
  everything:
    jobs:
      - "build"
